# Generated by Django 5.2.7 on 2025-10-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meeting",
            options={
                "ordering": ["-start_time"],
                "verbose_name": "Meeting",
                "verbose_name_plural": "Meetings",
            },
        ),
        migrations.AddField(
            model_name="meeting",
            name="minutes_file",
            field=models.FileField(
                blank=True,
                help_text="Upload the official minutes document (PDF, DOCX, etc.).",
                null=True,
                upload_to="meeting_minutes/",
            ),
        ),
    ]
